import React, { useState } from 'react';
import { Play, CheckCircle, RefreshCw, Cpu, Code2, AlertOctagon, Terminal, FileCheck, Layers, Sparkles, ArrowRight } from 'lucide-react';

/* -------------------------------------------------------------
   SIMULATOR 1: AI Testing Assistant (Agentic Workflow)
   ------------------------------------------------------------- */
export const AiTestingAssistantSimulator: React.FC = () => {
  const [selectedCase, setSelectedCase] = useState<'sap' | 'telecom'>('sap');
  const [stage, setStage] = useState<'idle' | 'running' | 'completed'>('idle');
  const [activeStep, setActiveStep] = useState<number>(0);

  const cases = {
    sap: {
      title: 'SAP SuccessFactors: Employee Address & Tax Location Change',
      input: 'Functional description: Employee initiates home address update in SuccessFactors profile. If state changes, system prompts for tax jurisdiction acknowledgment and recalculates state withholding tax.',
      requirements: [
        'REQ-SF-01: Profile address change form must validate postal code format against country rules.',
        'REQ-SF-02: Trigger asynchronous modal for tax jurisdiction recalculation when state changed.',
        'REQ-SF-03: Retain historical address effective dating audit trail in backend.',
      ],
      scenarios: [
        { id: 'SC-01', type: 'Positive', name: 'Valid intra-state address edit commits with immediate UI feedback.' },
        { id: 'SC-02', type: 'Negative', name: 'Invalid postal code triggers localized field error without modal trigger.' },
        { id: 'SC-03', type: 'Edge/Compliance', name: 'Inter-state change forces tax acknowledgment before final submission.' },
      ],
      rtm: [
        { req: 'REQ-SF-01', scenario: 'SC-01, SC-02', status: 'Covered', priority: 'High' },
        { req: 'REQ-SF-02', scenario: 'SC-03', status: 'Covered', priority: 'Critical' },
        { req: 'REQ-SF-03', scenario: 'SC-01 (Audit Check)', status: 'Covered', priority: 'High' },
      ],
      playwrightCode: `// Generated by AI Testing Assistant (Playwright + TypeScript POM)
import { test, expect } from '@playwright/test';
import { EmployeeProfilePage } from '../pages/EmployeeProfilePage';

test.describe('SAP SuccessFactors: Address & Tax Workflow', () => {
  test('should enforce tax jurisdiction acknowledgment on inter-state move', async ({ page }) => {
    const profilePage = new EmployeeProfilePage(page);
    
    // Seed authenticated session
    await profilePage.navigate();
    await profilePage.initiateAddressChange();
    
    // Fill updated address
    await profilePage.updateAddress({
      street: '742 Evergreen Terrace',
      city: 'Springfield',
      state: 'IL',
      zipCode: '62704'
    });
    
    // Assert tax modal presence
    await expect(page.getByRole('dialog', { name: /tax jurisdiction/i })).toBeVisible();
    await page.getByRole('button', { name: /acknowledge & confirm/i }).click();
    
    // Final save
    await profilePage.submitChange();
    await expect(page.getByText('Address successfully updated')).toBeVisible();
  });
});`,
    },
    telecom: {
      title: 'Telecom Self-Service: Postpaid Plan Upgrade & Payment Gateway',
      input: 'Functional description: Customer selects 5G Unlimited Postpaid plan upgrade, enters billing contact info, accepts prorated charge calculation, and pays via tokenized gateway.',
      requirements: [
        'REQ-TEL-101: Prorated bill preview calculated dynamically based on remaining billing cycle days.',
        'REQ-TEL-102: Payment gateway tokenization to prevent credit card storage in application backend.',
        'REQ-TEL-103: Immediate SMS and email confirmation dispatched upon payment success.',
      ],
      scenarios: [
        { id: 'SC-101', type: 'Positive', name: 'Successful plan upgrade with instant prorated fee payment.' },
        { id: 'SC-102', type: 'Negative', name: 'Gateway timeout rolls back plan selection without charging subscriber.' },
        { id: 'SC-103', type: 'Edge', name: 'Upgrade submitted on exact billing cycle boundary date (Day 30).' },
      ],
      rtm: [
        { req: 'REQ-TEL-101', scenario: 'SC-101, SC-103', status: 'Covered', priority: 'Critical' },
        { req: 'REQ-TEL-102', scenario: 'SC-101, SC-102', status: 'Covered', priority: 'High' },
        { req: 'REQ-TEL-103', scenario: 'SC-101', status: 'Covered', priority: 'Medium' },
      ],
      playwrightCode: `// Generated by AI Testing Assistant (Playwright + TypeScript)
import { test, expect } from '@playwright/test';
import { PlanUpgradePage } from '../pages/PlanUpgradePage';

test.describe('Telecom Self-Service: Postpaid Plan Upgrade', () => {
  test('should calculate prorated fee and process secure tokenized payment', async ({ page }) => {
    const upgradePage = new PlanUpgradePage(page);
    await upgradePage.goto();
    
    await upgradePage.selectPlan('5G-UNLIMITED-TIER1');
    const proratedAmount = await upgradePage.getProratedAmount();
    expect(proratedAmount).toBeGreaterThan(0);
    
    await upgradePage.proceedToPayment();
    await upgradePage.payWithMockToken('tok_visa_valid_3ds');
    
    await expect(page.getByRole('heading', { name: /Upgrade Confirmed/i })).toBeVisible();
  });
});`,
    },
  };

  const activeData = cases[selectedCase];

  const handleRun = () => {
    setStage('running');
    setActiveStep(1);

    setTimeout(() => setActiveStep(2), 600);
    setTimeout(() => setActiveStep(3), 1200);
    setTimeout(() => setActiveStep(4), 1800);
    setTimeout(() => {
      setActiveStep(5);
      setStage('completed');
    }, 2400);
  };

  const handleReset = () => {
    setStage('idle');
    setActiveStep(0);
  };

  return (
    <div className="rounded-sm border border-[#2A2A2A] bg-[#0C0C0C] p-5 sm:p-6 text-[#E0D8D0]">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-5 border-b border-[#222222] pb-4">
        <div>
          <div className="flex items-center gap-2">
            <Cpu className="w-4 h-4 text-[#C5A059]" />
            <h4 className="text-sm sm:text-base font-serif font-normal text-white">
              Live Interactive Prototype: AI Testing Assistant
            </h4>
          </div>
          <p className="text-xs text-[#8C8C8C] mt-0.5">
            Test the agentic pipeline: Screenshots/descriptions → Requirements → Scenarios → RTM → Playwright Code
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              setSelectedCase('sap');
              handleReset();
            }}
            className={`px-2.5 py-1 text-xs font-mono rounded-sm border transition-colors ${
              selectedCase === 'sap'
                ? 'bg-[#1A1813] text-[#C5A059] border-[#3E3420]'
                : 'bg-[#141414] text-[#8C8C8C] border-[#222222] hover:text-white'
            }`}
          >
            SAP Flow
          </button>
          <button
            onClick={() => {
              setSelectedCase('telecom');
              handleReset();
            }}
            className={`px-2.5 py-1 text-xs font-mono rounded-sm border transition-colors ${
              selectedCase === 'telecom'
                ? 'bg-[#1A1813] text-[#C5A059] border-[#3E3420]'
                : 'bg-[#141414] text-[#8C8C8C] border-[#222222] hover:text-white'
            }`}
          >
            Telecom Flow
          </button>
        </div>
      </div>

      {/* Input Stage */}
      <div className="mb-5 p-3.5 rounded-sm bg-[#121212] border border-[#222222] text-xs">
        <div className="flex items-center justify-between text-[#8C8C8C] font-mono mb-1.5">
          <span>Target Scenario Input:</span>
          <span className="text-[#C5A059]">Local Ollama LLM Mode</span>
        </div>
        <p className="text-[#C0B8AE] font-mono text-[12px] leading-relaxed mb-3">
          {activeData.input}
        </p>

        <div className="flex items-center justify-between pt-2 border-t border-[#1F1F1F]">
          <span className="text-[11px] text-[#666] font-mono">
            {selectedCase === 'sap' ? 'Context: 25+ SAP Processes Tested' : 'Context: 450+ Telecom Scripts'}
          </span>

          <button
            onClick={stage === 'completed' ? handleReset : handleRun}
            disabled={stage === 'running'}
            className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-sm text-xs font-sans uppercase tracking-widest font-semibold bg-[#1A1813] hover:bg-[#C5A059] text-[#C5A059] hover:text-black border border-[#3E3420] hover:border-[#C5A059] transition-all cursor-pointer shadow-md disabled:opacity-50"
          >
            {stage === 'running' ? (
              <>
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                <span>Running Multi-Agent Pipeline...</span>
              </>
            ) : stage === 'completed' ? (
              <>
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Reset Simulation</span>
              </>
            ) : (
              <>
                <Play className="w-3.5 h-3.5 fill-current" />
                <span>Execute Agentic Pipeline</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Progressive Output Stages */}
      {stage !== 'idle' && (
        <div className="space-y-4 pt-2">
          {/* Pipeline Stepper */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
            {[
              { num: 1, label: 'Requirements Ingestion' },
              { num: 2, label: 'Scenario Expansion' },
              { num: 3, label: 'Traceability Matrix (RTM)' },
              { num: 4, label: 'Playwright Code Synth' },
            ].map((st) => (
              <div
                key={st.num}
                className={`p-2 rounded-sm border flex items-center gap-2 transition-colors ${
                  activeStep >= st.num
                    ? 'bg-[#1A1813] text-[#C5A059] border-[#3E3420]'
                    : 'bg-[#121212] text-[#666] border-[#222222]'
                }`}
              >
                <span className="w-4 h-4 rounded-sm bg-[#241F14] text-[#C5A059] text-[10px] flex items-center justify-center font-bold">
                  {st.num}
                </span>
                <span className="truncate">{st.label}</span>
              </div>
            ))}
          </div>

          {/* Generated Artifacts Tabs */}
          {activeStep >= 2 && (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              {/* Left Column: Requirements & Scenarios */}
              <div className="space-y-3">
                <div className="p-3 rounded-sm bg-[#121212] border border-[#222222] text-xs">
                  <div className="flex items-center gap-1.5 font-sans uppercase tracking-wider text-[11px] text-[#C5A059] font-medium mb-2">
                    <FileCheck className="w-3.5 h-3.5" />
                    <span>Extracted Functional Requirements</span>
                  </div>
                  <ul className="space-y-1.5 text-[#C0B8AE]">
                    {activeData.requirements.map((r, i) => (
                      <li key={i} className="flex items-start gap-2">
                        <span className="text-[#C5A059] font-mono text-[10px]">✔</span>
                        <span>{r}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {activeStep >= 3 && (
                  <div className="p-3 rounded-sm bg-[#121212] border border-[#222222] text-xs">
                    <div className="flex items-center gap-1.5 font-sans uppercase tracking-wider text-[11px] text-[#C5A059] font-medium mb-2">
                      <Layers className="w-3.5 h-3.5" />
                      <span>Synthesized Test Scenarios (Edge & Boundary)</span>
                    </div>
                    <div className="space-y-1.5">
                      {activeData.scenarios.map((sc) => (
                        <div key={sc.id} className="flex items-center justify-between p-1.5 rounded-sm bg-[#0A0A0A] border border-[#222222]">
                          <span className="font-mono text-[#D4CDC5]">{sc.name}</span>
                          <span className="text-[10px] font-mono px-1.5 py-0.5 rounded-sm bg-[#161616] text-[#C5A059] border border-[#2A2A2A]">
                            {sc.type}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Right Column: Code Synthesis */}
              {activeStep >= 4 && (
                <div className="p-3 rounded-sm bg-[#080808] border border-[#222222] flex flex-col justify-between">
                  <div>
                    <div className="flex items-center justify-between font-mono text-xs text-[#8C8C8C] border-b border-[#222222] pb-2 mb-2">
                      <div className="flex items-center gap-1.5 text-[#C5A059] font-medium font-sans text-xs uppercase tracking-wider">
                        <Code2 className="w-3.5 h-3.5" />
                        <span>Generated Playwright Test (TypeScript)</span>
                      </div>
                      <span className="text-[10px] px-1.5 py-0.5 rounded-sm bg-[#111] text-[#A68846] border border-[#3E3420]">
                        POM Pattern
                      </span>
                    </div>
                    <pre className="font-mono text-[11px] text-[#C0B8AE] leading-tight overflow-x-auto max-h-[220px] p-2 bg-[#0E0E0E] rounded-sm border border-[#1A1A1A]">
                      <code>{activeData.playwrightCode}</code>
                    </pre>
                  </div>
                  <p className="text-[10px] font-mono text-[#666] mt-2">
                    * Generated locally via Ollama with zero external API calls.
                  </p>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
};

/* -------------------------------------------------------------
   SIMULATOR 2: AI Code Reviewer (Multi-Language Analyzer)
   ------------------------------------------------------------- */
export const AiCodeReviewerSimulator: React.FC = () => {
  const [language, setLanguage] = useState<'python' | 'typescript' | 'sql'>('python');
  const [analyzing, setAnalyzing] = useState<boolean>(false);
  const [reviewed, setReviewed] = useState<boolean>(false);

  const snippets = {
    python: {
      label: 'Python (Automation Script)',
      code: `# Fragile test script with hardcoded delays and raw locators
import time
from selenium import webdriver

driver = webdriver.Chrome()
driver.get("https://enterprise.portal/login")
time.sleep(5)  # Anti-pattern: Hardcoded arbitrary sleep
driver.find_element_by_xpath("/html/body/div[2]/form/input[1]").send_keys("admin")
driver.find_element_by_xpath("//button[@id='submit']").click()
time.sleep(3)
assert "Dashboard" in driver.title`,
      score: '5.8 / 10',
      smells: [
        'Hardcoded `time.sleep()` introduces flaky test runs and inflates suite execution duration.',
        'Brittle absolute XPath `/html/body/div[2]/...` breaks immediately upon DOM layout refactor.',
        'Direct browser driver instantiation without fixture or teardown try/finally lifecycle.',
      ],
      architecturalFixes: [
        'Adopt explicit expected condition waits (WebDriverWait) or switch to Playwright auto-waiting.',
        'Abstract locators into a Page Object Model class using user-facing role queries.',
      ],
    },
    typescript: {
      label: 'TypeScript (API Service Test)',
      code: `// Missing error boundaries and unhandled promise rejections
import axios from 'axios';

export async function verifyUserBalance(userId: string) {
  const res = await axios.get('http://api.internal/users/' + userId);
  // Vulnerability: No schema validation on payload
  if (res.data.balance < 0) {
    throw "Negative balance"; // Non-error object throw
  }
  return res.data;
}`,
      score: '6.2 / 10',
      smells: [
        'Non-Error throw: throwing raw string `"Negative balance"` loses call stack trace.',
        'Unvalidated payload schema creates runtime crashes if `balance` is undefined.',
        'Raw URL string concatenation lacks URL encoding protection against injection.',
      ],
      architecturalFixes: [
        'Throw standard \`new Error()\` instances or custom domain exception classes.',
        'Enforce type guard assertion or Zod schema validation on REST responses.',
      ],
    },
    sql: {
      label: 'SQL (Data Reconciliation / Backend)',
      code: `-- Unindexed cross-join table reconciliation
SELECT * FROM audit_logs
WHERE user_id IN (
  SELECT id FROM users WHERE status = 'ACTIVE'
)
AND action_timestamp > NOW() - INTERVAL '30 days';`,
      score: '6.5 / 10',
      smells: [
        '`SELECT *` retrieves unnecessary binary blobs and increases network I/O.',
        '`IN (subquery)` may degrade to sequential scan on large enterprise user tables.',
      ],
      architecturalFixes: [
        'Explicitly select required column projections to optimize memory buffers.',
        'Rewrite subquery as an indexed `INNER JOIN` or `EXISTS` clause.',
      ],
    },
  };

  const activeSnippet = snippets[language];

  const handleReview = () => {
    setAnalyzing(true);
    setTimeout(() => {
      setAnalyzing(false);
      setReviewed(true);
    }, 1000);
  };

  return (
    <div className="rounded-sm border border-[#2A2A2A] bg-[#0C0C0C] p-5 sm:p-6 text-[#E0D8D0]">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-5 border-b border-[#222222] pb-4">
        <div>
          <div className="flex items-center gap-2">
            <Code2 className="w-4 h-4 text-[#C5A059]" />
            <h4 className="text-sm sm:text-base font-serif font-normal text-white">
              Live Prototype: Multi-Language AI Code Reviewer
            </h4>
          </div>
          <p className="text-xs text-[#8C8C8C] mt-0.5">
            Local Ollama LLM analyzing code quality, anti-patterns, and architectural smells across 5+ languages
          </p>
        </div>

        <div className="flex items-center gap-1.5">
          {(['python', 'typescript', 'sql'] as const).map((lang) => (
            <button
              key={lang}
              onClick={() => {
                setLanguage(lang);
                setReviewed(false);
              }}
              className={`px-2.5 py-1 text-xs font-mono rounded-sm border transition-colors ${
                language === lang
                  ? 'bg-[#1A1813] text-[#C5A059] border-[#3E3420]'
                  : 'bg-[#141414] text-[#8C8C8C] border-[#222222] hover:text-white'
              }`}
            >
              {lang.toUpperCase()}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Code Input Window */}
        <div className="p-3 rounded-sm bg-[#080808] border border-[#222222] flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between text-xs font-mono text-[#8C8C8C] border-b border-[#222222] pb-2 mb-2">
              <span className="text-[#C0B8AE] font-semibold">{activeSnippet.label}</span>
              <span className="text-[10px] text-[#C5A059]">Input Source</span>
            </div>
            <pre className="font-mono text-xs text-[#C0B8AE] leading-relaxed overflow-x-auto p-2 bg-[#0E0E0E] rounded-sm border border-[#1A1A1A]">
              <code>{activeSnippet.code}</code>
            </pre>
          </div>

          <div className="pt-3 mt-3 border-t border-[#1F1F1F] flex items-center justify-between">
            <span className="text-[11px] font-mono text-[#666]">
              Privacy Mode: 100% Local Inference
            </span>
            <button
              onClick={handleReview}
              disabled={analyzing}
              className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-sm text-xs font-sans uppercase tracking-widest font-semibold bg-[#1A1813] hover:bg-[#C5A059] text-[#C5A059] hover:text-black border border-[#3E3420] hover:border-[#C5A059] transition-all cursor-pointer shadow-md disabled:opacity-50"
            >
              {analyzing ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>Analyzing AST & Smells...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-3.5 h-3.5 text-[#C5A059]" />
                  <span>Analyze with Ollama</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Structured Review Report */}
        <div className="p-3 rounded-sm bg-[#121212] border border-[#222222]">
          <div className="flex items-center justify-between text-xs font-mono border-b border-[#222222] pb-2 mb-3">
            <span className="text-white font-serif font-normal">Structured Review Output</span>
            {reviewed && (
              <span className="text-[10px] px-2 py-0.5 rounded-sm bg-[#1A1813] text-[#C5A059] border border-[#3E3420] font-mono font-bold">
                Quality: {activeSnippet.score}
              </span>
            )}
          </div>

          {!reviewed && !analyzing ? (
            <div className="h-[200px] flex flex-col items-center justify-center text-center p-4 text-[#666] text-xs font-mono">
              <Code2 className="w-8 h-8 text-[#444] mb-2 opacity-50" />
              <span>Click &quot;Analyze with Ollama&quot; to run local code smell and architectural inspection.</span>
            </div>
          ) : analyzing ? (
            <div className="h-[200px] flex flex-col items-center justify-center text-center p-4 text-[#C5A059] text-xs font-mono">
              <RefreshCw className="w-8 h-8 text-[#C5A059] animate-spin mb-2" />
              <span>Parsing tokens & evaluating code smells...</span>
            </div>
          ) : (
            <div className="space-y-3 text-xs">
              <div>
                <span className="font-sans uppercase tracking-wider text-[10px] text-rose-400 font-medium block mb-1.5">
                  ⚠ Detected Code Smells ({activeSnippet.smells.length})
                </span>
                <ul className="space-y-1 text-[#C0B8AE]">
                  {activeSnippet.smells.map((smell, i) => (
                    <li key={i} className="flex items-start gap-1.5">
                      <span className="text-rose-400 font-mono text-[10px]">✕</span>
                      <span>{smell}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="pt-2 border-t border-[#1F1F1F]">
                <span className="font-sans uppercase tracking-wider text-[10px] text-emerald-400 font-medium block mb-1.5">
                  ✔ Recommended Architectural Improvements
                </span>
                <ul className="space-y-1 text-[#C0B8AE]">
                  {activeSnippet.architecturalFixes.map((fix, i) => (
                    <li key={i} className="flex items-start gap-1.5">
                      <span className="text-emerald-400 font-mono text-[10px]">▸</span>
                      <span>{fix}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
